### ISSUE TITLE
Scan Sat

### ISSUE THREAD

**Issue by Sean1325** [Real-Gecko/KSP-Overdrive#2]
when I install the UI, scan sat doesn't work, I click on it - checked the console shows errors. remove UI works fine. I think you guys are aware or not I don't know but tell me how to fix it, please.

**Comment by HebaruSan** [comment]
According to @DMagic1, [Overdrive removes the stock `HighLogic.Skin.toggle` object and doesn't replace it with anything](https://github.com/KSP-CKAN/NetKAN/pull/6187#issuecomment-359047588).

https://github.com/Real-Gecko/KSP-Overdrive/blob/4305d96bdd8fb5b99769b8fa4dc537a5eb63f8fb/Overdrive/Overdrive.cs#L259

However, just removing that line isn't necessarily the answer. The replacement object ought to exist, and the specific `.background` properties that crash SCANSat are set in the cfg:

https://github.com/Real-Gecko/KSP-Overdrive/blob/4305d96bdd8fb5b99769b8fa4dc537a5eb63f8fb/GameData/Overdrive/Skins/Overdrive/Overdrive.cfg#L164-L182

Further note for anyone considering a pull request, ownership of this mod is now transferred to: https://github.com/linuxgurugamer/KSP-Overdrive

**Comment by Sean1325** [comment]
Oh Ok, but it's weird it seems only to remove scan sag completely without
the parts of course but it's a nice mod. Thanks for the reply and I play on
Mac os but I doubt it changes anything, if you need my help please contact
me.

**Comment by Real-Gecko** [comment]
@linuxgurugamer is now in charge for this mod, I think he'll fix the issue in no time.
